// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8PNlj8rgp1zG5XKA96MCJc43LhS5LiFY',
    appId: '1:123623889213:web:09d7ae16704d86f9d70d54',
    messagingSenderId: '123623889213',
    projectId: 'slicksync-afd0d',
    authDomain: 'slicksync-afd0d.firebaseapp.com',
    storageBucket: 'slicksync-afd0d.firebasestorage.app',
    measurementId: 'G-BT5095E7TH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwchL077Ky136NZ8QNRcKLm2Nv1UoBuvs',
    appId: '1:123623889213:android:ca028db5881aed3bd70d54',
    messagingSenderId: '123623889213',
    projectId: 'slicksync-afd0d',
    storageBucket: 'slicksync-afd0d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUpJ6i8rZSPgT2PU6vNgPPZG4b6qbnVuM',
    appId: '1:123623889213:ios:2e50c7f1655a4000d70d54',
    messagingSenderId: '123623889213',
    projectId: 'slicksync-afd0d',
    storageBucket: 'slicksync-afd0d.firebasestorage.app',
    iosBundleId: 'com.example.firstGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUpJ6i8rZSPgT2PU6vNgPPZG4b6qbnVuM',
    appId: '1:123623889213:ios:2e50c7f1655a4000d70d54',
    messagingSenderId: '123623889213',
    projectId: 'slicksync-afd0d',
    storageBucket: 'slicksync-afd0d.firebasestorage.app',
    iosBundleId: 'com.example.firstGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8PNlj8rgp1zG5XKA96MCJc43LhS5LiFY',
    appId: '1:123623889213:web:e029766e0495e14fd70d54',
    messagingSenderId: '123623889213',
    projectId: 'slicksync-afd0d',
    authDomain: 'slicksync-afd0d.firebaseapp.com',
    storageBucket: 'slicksync-afd0d.firebasestorage.app',
    measurementId: 'G-QEY3DH5GH3',
  );
}
